apiVersion: v1
kind: Pod
metadata:
  name: personal-site
spec:
  containers:
    - image: alecashford/personal_site
      # imagePullPolicy: IfNotPresent
      name: personal-site
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
